version: '3.9'

x-app: &default-app
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    ENVIRONMENT: production
  depends_on:
    database:
      condition: service_healthy

services:
  app:
    <<: *default-app
    container_name: app
    ports:
      - 8000:80
    command: [ "sh", "run.sh"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health-check" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart:
      always

  database:
    image: library/postgres:alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shop_list
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s